version: "3"
services:
  db:
    image: postgres:12.0
    restart: always
    environment:
      POSTGRES_PASSWORD: ${JNA_DB_PASSWORD}
      POSTGRES_USER: ${JNA_DB_USER}
      POSTGRES_DB: ${JNA_DB_NAME}
    ports:
      - "15432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  api:
    depends_on:
      - db
    build: java
    environment:
        JNA_DB_PASSWORD: ${JNA_DB_PASSWORD}
        JNA_DB_URL: ${JNA_DB_URL}
        JNA_DB_USER: ${JNA_DB_NAME}
        JNA_SALT: ${JNA_SALT}
    restart: always
    ports:
      - "9001:3456"

  ui:
    depends_on:
    - api
    build: javascript
    restart: always
    ports:
      - "8001:5000"
