version: "3"
services:
  db:
    image: postgres:12.0
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: local
      POSTGRES_DB: JNA
    ports:
      - "15432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  api:
    depends_on:
      - db
    build: java
    restart: always
    ports:
      - "9001:3456"

  ui:
    depends_on:
    - api
    build: javascript
    restart: always
    ports:
      - "8001:5000"
